"""Public project schema and IO API."""

from predici_clone.api.project_io import load_project, save_project
from predici_clone.api.cape_open import CapeOpenCapability, cape_open_capability, cape_open_manifest
from predici_clone.api.automation import (
    activate_detailed_iteration,
    check_enthalpy,
    create_recipe,
    get_dist_moments,
    get_dist_points,
    get_reactor_pressure,
    set_dist_lumping,
    set_enthalpy,
    set_feed_rate,
    set_heat_exchanger,
)
from predici_clone.api.packaging_smoke import PackagingSmokeReport, inspect_pyinstaller_packaging
from predici_clone.api.interoperability import (
    execute_public_command,
    export_c_moment_equations,
    export_matlab_moment_equations,
)
from predici_clone.api.recipe_profiles import (
    add_feed_tank,
    add_polymer_feed,
    append_pre_schedule_step,
    apply_pre_schedule,
    effective_feed_stream,
    effective_polymer_feed_rate,
    evaluate_profile,
    scheduled_additional_heat,
    scheduled_coolant_temperature,
    scheduled_pressure,
    scheduled_residence_time,
    scheduled_temperature,
    scheduled_feed_rate,
    set_pressure_profile,
    set_temperature_profile,
)
from predici_clone.api.result_io import load_result_manifest, save_simulation_result
from predici_clone.api.spatial_profiles import FeedProfile, FlowDist, FluidBalance, flow_solve, fluid_balance
from predici_clone.api.validation import ValidationMessage, validate_project, validation_summary
from predici_clone.api.project_schema import (
    FeedStream,
    FRPParameters,
    GeneralKineticParticipant,
    GeneralKineticStep,
    HeatBalanceConfig,
    InitialConditions,
    IntegrationControl,
    OutputConfig,
    ProfilePoint,
    Project,
    Recipe,
    ReactorConfig,
)

__all__ = [
    "FRPParameters",
    "CapeOpenCapability",
    "FeedProfile",
    "FeedStream",
    "FlowDist",
    "FluidBalance",
    "GeneralKineticParticipant",
    "GeneralKineticStep",
    "HeatBalanceConfig",
    "InitialConditions",
    "IntegrationControl",
    "OutputConfig",
    "PackagingSmokeReport",
    "ProfilePoint",
    "Project",
    "ReactorConfig",
    "Recipe",
    "activate_detailed_iteration",
    "add_feed_tank",
    "add_polymer_feed",
    "append_pre_schedule_step",
    "apply_pre_schedule",
    "check_enthalpy",
    "cape_open_capability",
    "cape_open_manifest",
    "create_recipe",
    "evaluate_profile",
    "execute_public_command",
    "effective_feed_stream",
    "effective_polymer_feed_rate",
    "export_c_moment_equations",
    "export_matlab_moment_equations",
    "fluid_balance",
    "flow_solve",
    "scheduled_additional_heat",
    "scheduled_coolant_temperature",
    "scheduled_feed_rate",
    "scheduled_pressure",
    "scheduled_residence_time",
    "scheduled_temperature",
    "get_reactor_pressure",
    "get_dist_moments",
    "get_dist_points",
    "inspect_pyinstaller_packaging",
    "load_result_manifest",
    "load_project",
    "save_simulation_result",
    "save_project",
    "set_dist_lumping",
    "set_feed_rate",
    "set_pressure_profile",
    "set_enthalpy",
    "set_heat_exchanger",
    "set_temperature_profile",
    "ValidationMessage",
    "validate_project",
    "validation_summary",
]
